package com.threego.app.ws;

public enum MessageType {
	NEW_BOARD_COMMENT,
	WARNING_CAUTION_BY_RIDER,
	WARNING_CAUTION_BY_WRITER,
	CANCELED_REQUEST,
	COMPLETE_REQUEST,
	RIDER_APPROVEMENT,
	RIDER_REFUSAL;
}
